name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run package

      - name: Publish pre-release to VS Code Marketplace
        run: npm run vsce:publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
